name: Swift

on: [push]

jobs:
  test-original:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install swiftenv
      run: |-
        brew install kylef/formulae/swiftenv
        echo 'if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi' >> ~/.bash_profile
    - name: Install Swift
      run: |-
        if ! (swiftenv versions | grep "*"); then
          echo "Swift version not found. Installing..."
          swiftenv install
        fi
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  test-vapor-macos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest
          - latest-stable
    runs-on: macos-11
    steps: 
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Check out Vapor
        uses: actions/checkout@v2
      - name: Run main tests with Thread Sanitizer
        run: |
          swift test --filter '^VaporTests' --sanitize=thread -Xlinker -rpath \
                -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx
      - name: Run async tests without Thread Sanitizer
        # TSAN and async don't play nice at the moment
        run: |
          swift test --filter '^AsyncTests' -Xlinker -rpath \
                -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx
