name: Swift

on: [push]

jobs:
  
  test-vapor-linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.3-focal
          - swift:5.4-focal
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Check out Vapor
        uses: actions/checkout@v2
      - name: Run main tests
        run: swift test --enable-test-discovery
 
